# -*- coding: utf-8 -*-
"""part2_order_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsGZ8C5UGWH4n6bEoX0lECI3EXKQcmV0
"""

menu = {
    "Paneer Tikka":   {"category": "Starters",  "price": 180.0, "available": True},
    "Chicken Wings":  {"category": "Starters",  "price": 220.0, "available": False},
    "Veg Soup":       {"category": "Starters",  "price": 120.0, "available": True},
    "Butter Chicken": {"category": "Mains",     "price": 320.0, "available": True},
    "Dal Tadka":      {"category": "Mains",     "price": 180.0, "available": True},
    "Veg Biryani":    {"category": "Mains",     "price": 250.0, "available": True},
    "Garlic Naan":    {"category": "Mains",     "price":  40.0, "available": True},
    "Gulab Jamun":    {"category": "Desserts",  "price":  90.0, "available": True},
    "Rasgulla":       {"category": "Desserts",  "price":  80.0, "available": True},
    "Ice Cream":      {"category": "Desserts",  "price": 110.0, "available": False},
}

inventory = {
    "Paneer Tikka":   {"stock": 10, "reorder_level": 3},
    "Chicken Wings":  {"stock":  8, "reorder_level": 2},
    "Veg Soup":       {"stock": 15, "reorder_level": 5},
    "Butter Chicken": {"stock": 12, "reorder_level": 4},
    "Dal Tadka":      {"stock": 20, "reorder_level": 5},
    "Veg Biryani":    {"stock":  6, "reorder_level": 3},
    "Garlic Naan":    {"stock": 30, "reorder_level": 10},
    "Gulab Jamun":    {"stock":  5, "reorder_level": 2},
    "Rasgulla":       {"stock":  4, "reorder_level": 3},
    "Ice Cream":      {"stock":  7, "reorder_level": 4},
}

sales_log = {
    "2025-01-01": [
        {"order_id": 1,  "items": ["Paneer Tikka", "Garlic Naan"],          "total": 220.0},
        {"order_id": 2,  "items": ["Gulab Jamun", "Veg Soup"],              "total": 210.0},
        {"order_id": 3,  "items": ["Butter Chicken", "Garlic Naan"],        "total": 360.0},
    ],
    "2025-01-02": [
        {"order_id": 4,  "items": ["Dal Tadka", "Garlic Naan"],             "total": 220.0},
        {"order_id": 5,  "items": ["Veg Biryani", "Gulab Jamun"],           "total": 340.0},
    ],
    "2025-01-03": [
        {"order_id": 6,  "items": ["Paneer Tikka", "Rasgulla"],             "total": 260.0},
        {"order_id": 7,  "items": ["Butter Chicken", "Veg Biryani"],        "total": 570.0},
        {"order_id": 8,  "items": ["Garlic Naan", "Gulab Jamun"],           "total": 130.0},
    ],
    "2025-01-04": [
        {"order_id": 9,  "items": ["Dal Tadka", "Garlic Naan", "Rasgulla"], "total": 300.0},
        {"order_id": 10, "items": ["Paneer Tikka", "Gulab Jamun"],          "total": 270.0},
    ],
}

menu = {
    "Paneer Tikka":   {"category": "Starters",  "price": 180.0, "available": True},
    "Chicken Wings":  {"category": "Starters",  "price": 220.0, "available": False},
    "Veg Soup":       {"category": "Starters",  "price": 120.0, "available": True},
    "Butter Chicken": {"category": "Mains",     "price": 320.0, "available": True},
    "Dal Tadka":      {"category": "Mains",     "price": 180.0, "available": True},
    "Veg Biryani":    {"category": "Mains",     "price": 250.0, "available": True},
    "Garlic Naan":    {"category": "Mains",     "price":  40.0, "available": True},
    "Gulab Jamun":    {"category": "Desserts",  "price":  90.0, "available": True},
    "Rasgulla":       {"category": "Desserts",  "price":  80.0, "available": True},
    "Ice Cream":      {"category": "Desserts",  "price": 110.0, "available": False},
}

# --- 1. Print Menu Grouped by Category ---
# First, let's define the order we want categories to appear in
categories = ["Starters", "Mains", "Desserts"]

for cat in categories:
    print(f"===== {cat} =====")

    # Nested loop to filter items by the current category
    for item, details in menu.items():
        if details["category"] == cat:
            price = details["price"]
            # Ternary operator for availability text
            status = "Available" if details["available"] else "Unavailable"

            # Formatting: Left-aligned name (15 chars), Right-aligned price
            print(f"{item:<17} ₹{price:>6.2f}   [{status}]")
    print() # Add space between sections

# --- 2. Menu Statistics ---
print("--- Menu Insights ---")

# A. Total items
total_items = len(menu)

# B. Total available items (using a generator expression)
available_count = sum(1 for item in menu.values() if item["available"])

# C. Most expensive item
# We use the 'key' argument in max() to tell Python to look at the 'price' sub-key
most_expensive_name = max(menu, key=lambda x: menu[x]["price"])
most_expensive_price = menu[most_expensive_name]["price"]

# D. Items under ₹150
# List comprehension to filter the items
budget_items = [(name, data["price"]) for name, data in menu.items() if data["price"] < 150]

print(f"Total Items         : {total_items}")
print(f"Available Items     : {available_count}")
print(f"Most Expensive      : {most_expensive_name} (₹{most_expensive_price:.2f})")

print("\nBudget Friendly (Under ₹150):")
for name, price in budget_items:
    print(f"- {name}: ₹{price:.2f}")

#  menu  already defined
menu = {
    "Paneer Tikka":   {"category": "Starters",  "price": 180.0, "available": True},
    "Chicken Wings":  {"category": "Starters",  "price": 220.0, "available": False},
    "Veg Soup":       {"category": "Starters",  "price": 120.0, "available": True},
    "Butter Chicken": {"category": "Mains",     "price": 320.0, "available": True},
    "Dal Tadka":      {"category": "Mains",     "price": 180.0, "available": True},
    "Veg Biryani":    {"category": "Mains",     "price": 250.0, "available": True},
    "Garlic Naan":    {"category": "Mains",     "price":  40.0, "available": True},
    "Gulab Jamun":    {"category": "Desserts",  "price":  90.0, "available": True},
    "Rasgulla":       {"category": "Desserts",  "price":  80.0, "available": True},
    "Ice Cream":      {"category": "Desserts",  "price": 110.0, "available": False},
}

cart = []

def add_to_cart(item_name, quantity):
    # 1. Check if item exists in menu
    if item_name not in menu:
        print(f"✗ Error: '{item_name}' is not on the menu.")
        return

    # 2. Check if item is available
    if not menu[item_name]["available"]:
        print(f"✗ Error: '{item_name}' is currently unavailable.")
        return

    # 3. Check if already in cart to avoid duplicates
    for entry in cart:
        if entry["item"] == item_name:
            entry["quantity"] += quantity
            print(f"✓ Updated {item_name} quantity to {entry['quantity']}.")
            return

    # 4. Add new entry if not a duplicate
    cart.append({
        "item": item_name,
        "quantity": quantity,
        "price": menu[item_name]["price"]
    })
    print(f"✓ Added {quantity}x {item_name} to cart.")

def remove_from_cart(item_name):
    for i, entry in enumerate(cart):
        if entry["item"] == item_name:
            cart.pop(i)
            print(f"✓ Removed {item_name} from cart.")
            return
    print(f"✗ Error: {item_name} not found in cart.")

# --- SIMULATION ---
print("--- Starting Simulation ---")

add_to_cart("Paneer Tikka", 2)
add_to_cart("Gulab Jamun", 1)
add_to_cart("Paneer Tikka", 1)  # Testing duplicate logic
add_to_cart("Mystery Burger", 1) # Testing existence check
add_to_cart("Chicken Wings", 1)  # Testing availability check
remove_from_cart("Gulab Jamun")  # Testing removal

# --- FINAL ORDER SUMMARY ---
print("\n" + "="*36)
print(f"{'Order Summary':^36}")
print("="*36)

subtotal = 0
for entry in cart:
    item_total = entry["price"] * entry["quantity"]
    subtotal += item_total
    print(f"{entry['item']:<18} x{entry['quantity']}    ₹{item_total:>7.2f}")

gst = subtotal * 0.05
total_payable = subtotal + gst

print("-" * 36)
print(f"{'Subtotal:':<25} ₹{subtotal:>8.2f}")
print(f"{'GST (5%):':<25} ₹{gst:>8.2f}")
print(f"{'Total Payable:':<25} ₹{total_payable:>8.2f}")
print("=" * 36)



import copy

# Provided Data
inventory = {
    "Paneer Tikka":   {"stock": 10, "reorder_level": 3},
    "Chicken Wings":  {"stock":  8, "reorder_level": 2},
    "Veg Soup":       {"stock": 15, "reorder_level": 5},
    "Butter Chicken": {"stock": 12, "reorder_level": 4},
    "Dal Tadka":      {"stock": 20, "reorder_level": 5},
    "Veg Biryani":    {"stock":  6, "reorder_level": 3},
    "Garlic Naan":    {"stock": 30, "reorder_level": 10},
    "Gulab Jamun":    {"stock":  5, "reorder_level": 2},
    "Rasgulla":       {"stock":  4, "reorder_level": 3},
    "Ice Cream":      {"stock":  7, "reorder_level": 4},
}

# The cart from Task 2: Paneer Tikka x 3
final_cart = [{"item": "Paneer Tikka", "quantity": 3, "price": 180.0}]

# STEP 1: Deep Copy
inventory_backup = copy.deepcopy(inventory)

# STEP 2: Proof of Deep Copy
print("*** Deep Copy Verification ***")
inventory["Paneer Tikka"]["stock"] = 999
print(f"Inventory 'Paneer Tikka' stock (Modified): {inventory['Paneer Tikka']['stock']}")
print(f"Backup 'Paneer Tikka' stock (Original): {inventory_backup['Paneer Tikka']['stock']}")

# Restore to original state for the rest of the task
inventory["Paneer Tikka"]["stock"] = 10
print("✓ Inventory restored for processing.\n")

# STEP 3: Order Fulfillment
print("*** Processing Order Fulfillment ***")
for entry in final_cart:
    item = entry["item"]
    qty_needed = entry["quantity"]

    if item in inventory:
        current_stock = inventory[item]["stock"]

        if current_stock >= qty_needed:
            inventory[item]["stock"] -= qty_needed
            print(f"Deducted {qty_needed} {item} from stock.")
        else:
            # Handle insufficient stock
            print(f"⚠ Warning: Insufficient stock for {item}. Only {current_stock} available.")
            inventory[item]["stock"] = 0

# --- STEP 4: Reorder Alerts ---
print("\n***Inventory Alerts ***")
for item, details in inventory.items():
    stock = details["stock"]
    level = details["reorder_level"]

    if stock <= level:
        print(f"⚠ Reorder Alert: {item} — Only {stock} unit(s) left (reorder level: {level})")

# --- FINAL COMPARISON ---
print("\n***Final Integrity Check***")
print(f"Final Inventory (Paneer Tikka): {inventory['Paneer Tikka']['stock']}")
print(f"Backup Inventory (Paneer Tikka): {inventory_backup['Paneer Tikka']['stock']}")

sales_log = {
    "2025-01-01": [
        {"order_id": 1,  "items": ["Paneer Tikka", "Garlic Naan"],          "total": 220.0},
        {"order_id": 2,  "items": ["Gulab Jamun", "Veg Soup"],              "total": 210.0},
        {"order_id": 3,  "items": ["Butter Chicken", "Garlic Naan"],        "total": 360.0},
    ],
    "2025-01-02": [
        {"order_id": 4,  "items": ["Dal Tadka", "Garlic Naan"],             "total": 220.0},
        {"order_id": 5,  "items": ["Veg Biryani", "Gulab Jamun"],           "total": 340.0},
    ],
    "2025-01-03": [
        {"order_id": 6,  "items": ["Paneer Tikka", "Rasgulla"],             "total": 260.0},
        {"order_id": 7,  "items": ["Butter Chicken", "Veg Biryani"],        "total": 570.0},
        {"order_id": 8,  "items": ["Garlic Naan", "Gulab Jamun"],           "total": 130.0},
    ],
    "2025-01-04": [
        {"order_id": 9,  "items": ["Dal Tadka", "Garlic Naan", "Rasgulla"], "total": 300.0},
        {"order_id": 10, "items": ["Paneer Tikka", "Gulab Jamun"],          "total": 270.0},
    ],
}

# STEP 1: Add New Data
sales_log["2025-01-05"] = [
    {"order_id": 11, "items": ["Butter Chicken", "Gulab Jamun", "Garlic Naan"], "total": 490.0},
    {"order_id": 12, "items": ["Paneer Tikka", "Rasgulla"],                     "total": 260.0},
]

#  STEP 2: Revenue Analysis Function
def analyze_sales(log):
    daily_revenue = {}
    item_frequency = {}

    for date, orders in log.items():
        day_total = 0
        for order in orders:
            day_total += order["total"]
            # Count item occurrences across all orders
            for item in order["items"]:
                item_frequency[item] = item_frequency.get(item, 0) + 1

        daily_revenue[date] = day_total

    return daily_revenue, item_frequency

# Execute Analysis
rev_stats, item_stats = analyze_sales(sales_log)

# --- STEP 3: Print Reports ---
print("Daily Revenue Table")
for date, total in rev_stats.items():
    print(f"{date} : ₹{total:>8.2f}")

# Find Best Selling Day
best_day = max(rev_stats, key=rev_stats.get)
print(f"\nBest-Selling Day: {best_day} (₹{rev_stats[best_day]:.2f})")

# Find Most Ordered Item
most_ordered = max(item_stats, key=item_stats.get)
print(f"Most Ordered Item: {most_ordered} (Found in {item_stats[most_ordered]} orders)")

#  STEP 4: Numbered Order List
print("\nFull Transaction History ")
all_orders_list = []

# Flatten the log into a single list for enumeration
for date, orders in sales_log.items():
    for order in orders:
        all_orders_list.append((date, order))

for i, (date, order) in enumerate(all_orders_list, start=1):
    # Join items into a comma-separated string
    items_str = ", ".join(order['items'])
    print(f"{i}. [{date}] Order #{order['order_id']:<2} — ₹{order['total']:>6.2f} — Items: {items_str}")